# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: quteo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - quteo:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  quteo:
